github actions: many improvements (#7)
- Have gofmt and misspell checks post a comment.
- Have many steps run even if a previous step failed.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,11 +3,13 @@
 # that can be found in the LICENSE file.
 
 # References:
-# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
-# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions/
+# https://developer.github.com/webhooks/event-payloads/
 # https://github.com/actions/cache
 # https://github.com/actions/checkout
 # https://github.com/actions/setup-go
+# https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow
+# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions/
+# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
 
 on: [push, pull_request]
 name: Run tests
@@ -44,7 +46,7 @@ jobs:
         golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
         honnef.co/go/tools/cmd/staticcheck
     - name: "Debug (posix)"
-      if: matrix.os != 'windows-latest'
+      if: always() && matrix.os != 'windows-latest'
       run: |
         echo GOPATH = $GOPATH
         echo GOROOT = $GOROOT
@@ -65,7 +67,7 @@ jobs:
         echo $ ls -la $HOME/go/bin
         ls -la $HOME/go/bin
     - name: "Debug (windows)"
-      if: matrix.os == 'windows-latest'
+      if: always() && matrix.os == 'windows-latest'
       shell: cmd
       run: |
         echo GOPATH = %GOPATH%
@@ -79,62 +81,97 @@ jobs:
         dir /a %USERPROFILE%\go
         dir /a %USERPROFILE%\go\bin
     - name: 'Check: go vet'
+      if: always()
       run: go vet ./...
     - name: 'Check: go vet shadow; shadowed variables (posix)'
-      if: matrix.os != 'windows-latest'
+      if: always() && matrix.os != 'windows-latest'
       run: go vet -vettool=$(which shadow) ./...
-      #  |& grep -v '"err"' | grep -e '^[^#]'
     - name: 'Check: go vet shadow; shadowed variables (windows)'
-      if: matrix.os == 'windows-latest'
+      if: always() && matrix.os == 'windows-latest'
       shell: cmd
       run: go vet -vettool=%USERPROFILE%/go/bin/shadow.exe ./...
     - name: 'Check: golint'
+      if: always()
       run: golint -set_exit_status ./...
     - name: 'Check: inefficient variable assignment'
+      if: always()
       run: ineffassign .
     - name: 'Check: staticcheck'
+      if: always()
       run: staticcheck -checks -U1000 ./...
 
       # The following checks are not dependent on the OS or go build tags. Only
       # run them on ubuntu-latest since it's the fastest one.
     - name: 'go get necessary tools (ubuntu)'
-      if: matrix.os == 'ubuntu-latest'
+      if: always() && matrix.os == 'ubuntu-latest'
       run: >
         go get -u
         github.com/client9/misspell/cmd/misspell
         github.com/google/addlicense
     - name: 'Check: no executable was committed (ubuntu)'
-      if: matrix.os == 'ubuntu-latest'
-      run: if find . -path ./systemd/setup.sh -prune -o -path ./.git -prune -o -type f -executable -print | grep -e . ; then echo 'Do not commit executables'; false; fi
-    - name: 'Check: gofmt; code is well formatted (ubuntu)'
-      if: matrix.os == 'ubuntu-latest'
+      if: always() && matrix.os == 'ubuntu-latest'
       run: |
-        DIFF=$(sh -c "gofmt -s ." 2>&1)
-        DIFF="$(gofmt -s -d .)"
-        if ! test -z "$DIFF"; then
-          echo "$DIFF"
+        if find . -path ./systemd/setup.sh -prune -o -path ./.git -prune -o -type f -executable -print | grep -e . ; then
+          echo 'Do not commit executables'
+          false
+        fi
+    - name: 'Check: gofmt; code is well formatted (ubuntu)'
+      if: always() && matrix.os == 'ubuntu-latest'
+      run: |
+        FILES=$(gofmt -s -l .)
+        if ! test -z "$FILES"; then
+          echo 'Please run `gofmt -s -w` on the following files:' >> _gofmt.txt
+          echo "" >> _gofmt.txt
+          for FILE in ${FILES}; do
+            echo "- ${FILE}" >> _gofmt.txt
+          done
+          cat _gofmt.txt
+          echo "## ⚠ gofmt Failed" >> _comments.txt
+          echo "" >> _comments.txt
+          cat _gofmt.txt >> _comments.txt
+          echo "" >> _comments.txt
           false
         fi
     - name: 'Check: addlicense; all sources have a license header (ubuntu)'
-      if: matrix.os == 'ubuntu-latest'
+      if: always() && matrix.os == 'ubuntu-latest'
       run: addlicense -check .
     - name: "Check: misspelling; code doesn't contain misspelling (ubuntu)"
-      if: matrix.os == 'ubuntu-latest'
+      if: always() && matrix.os == 'ubuntu-latest'
       run: |
         ERR=$(misspell .)
         if ! test -z "$ERR"; then
           echo "$ERR"
+          echo "## ⚠ misspell Failed" >> _comments.txt
+          echo "" >> _comments.txt
+          echo "$ERR" >> _comments.txt
+          echo "" >> _comments.txt
           false
         fi
+
       # Run tests last since it's potentially the slowest step.
     - name: 'Check: go test -cover (posix)'
-      if: matrix.os != 'windows-latest'
+      if: always() && matrix.os != 'windows-latest'
       run: go test -covermode=count -coverprofile=coverage.txt ./...
     - name: 'Check: go test -cover (windows)'
-      if: matrix.os == 'windows-latest'
+      if: always() && matrix.os == 'windows-latest'
       # Powershell messes things up.
       shell: cmd
       run: go test -covermode=count -coverprofile=coverage.txt ./...
+      # Don't send code coverage if anything failed to reduce spam.
     - uses: codecov/codecov-action@v1
+      # Don't run go test -race if anything failed, to speed up the results.
     - name: 'Check: go test -race'
       run: go test -race ./...
+
+    - name: 'Send comments (posix)'
+      if: failure() && matrix.os != 'windows-latest' && github.event_name == 'pull_request'
+      run: |
+        if [ -f _comments.txt ]; then
+          URL=$(cat ${GITHUB_EVENT_PATH} | jq -r .pull_request.comments_url)
+          echo "Sending $(cat _comments.txt|wc -l) lines of comments to ${URL}"
+          PAYLOAD=$(echo '{}' | jq --arg body "$(cat _comments.txt)" '.body = $body')
+          curl -sS --request POST \
+            --header "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
+            --header "Content-Type: application/json" \
+            --data "${PAYLOAD}" "${URL}" > /dev/null
+        fi
